# How to access duplicate rows

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Chembl_library_2M_2.csv')
df.head()

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (27) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,ChEMBLID,Name,Synonyms,Type,MaxPhase,MolecularWeight,Targets,Bioactivities,AlogP,PolarSurfaceArea,...,InorganicFlag,HeavyAtoms,HBA(Lipinski),HBD(Lipinski),#RO5Violations(Lipinski),MolecularWeight(Monoisotopic),MolecularSpecies,MolecularFormula,Smiles,InchiKey
0,CHEMBL3425773,NaN,NaN,Small molecule,0,263.25,1.0,1.0,3.04,74.23,...,-1,20,4,1,0,263.0582,ACID,C16H9NO3,N#Cc1ccc(-c2coc3cc(O)ccc3c2=O)cc1,VFISVTBQGUQPIQ-UHFFFAOYSA-N
1,CHEMBL1998753,NaN,NaN,Small molecule,0,455.46,56.0,56.0,2.28,100.60,...,-1,33,9,0,0,455.158,NEUTRAL,C24H25NO8,COC(=O)[C@@H]1[C@H]2[C@H](OC(=O)c3ccccc3)CCN2O...,OQFYYDNHLYZLOL-BORCDFBASA-N
2,CHEMBL1867860,NaN,NaN,Small molecule,0,465.53,4.0,4.0,3.49,91.56,...,-1,33,8,1,0,465.1358,NEUTRAL,C24H23N3O5S,COc1cccc(-n2c(=O)c3c(C)c(C)sc3n(CC(=O)Nc3ccccc...,CHCLAAKAFOYXSQ-UHFFFAOYSA-N
3,CHEMBL481686,NaN,NaN,Small molecule,0,417.55,1.0,2.0,4.71,48.71,...,-1,31,5,1,0,417.2416,NEUTRAL,C26H31N3O2,Cc1cc(C)cc(N(Cc2ccc(CO)cc2)c2cc(C(=O)N3CCCC3)n...,UFQDWXYZGWHYFO-UHFFFAOYSA-N
4,CHEMBL1939547,NaN,NaN,Small molecule,0,328.31,5.0,10.0,3.69,112.06,...,-1,23,8,0,0,328.0266,NEUTRAL,C14H8N4O4S,O=[N+]([O-])c1ccc(-c2nsc(-c3ccc([N+](=O)[O-])c...,VCXUCYVZJDYDCE-UHFFFAOYSA-N

In [ ]:
df2 = df[['ChEMBLID', 'MolecularWeight','AlogP', 'MolecularSpecies', 'Smiles']]
df2

,ChEMBLID,MolecularWeight,AlogP,MolecularSpecies,Smiles
0,CHEMBL3425773,263.25,3.04,ACID,N#Cc1ccc(-c2coc3cc(O)ccc3c2=O)cc1
1,CHEMBL1998753,455.46,2.28,NEUTRAL,COC(=O)[C@@H]1[C@H]2[C@H](OC(=O)c3ccccc3)CCN2O...
2,CHEMBL1867860,465.53,3.49,NEUTRAL,COc1cccc(-n2c(=O)c3c(C)c(C)sc3n(CC(=O)Nc3ccccc...
3,CHEMBL481686,417.55,4.71,NEUTRAL,Cc1cc(C)cc(N(Cc2ccc(CO)cc2)c2cc(C(=O)N3CCCC3)n...
4,CHEMBL1939547,328.31,3.69,NEUTRAL,O=[N+]([O-])c1ccc(-c2nsc(-c3ccc([N+](=O)[O-])c...
...,...,...,...,...,...
1920333,CHEMBL1627004,1815.46,NaN,None,CC(C)C[C@H](NC(=O)[C@H](CC(=O)OS(=O)(=O)[O-])N...
1920334,CHEMBL3958686,450.53,1.33,NEUTRAL,Cc1c(Cc2ccc(OC(C)C)cc2)c(O[C@@H]2O[C@H](CO)[C@...
1920335,CHEMBL1201377,368.51,3.87,ACID,CCCCC(C)(O)C/C=C/[C@H]1[C@H](O)CC(=O)[C@@H]1CC...
1920336,CHEMBL537710,375.76,0.82,ACID,Cl.NS(=O)(=O)c1ccc(NC(=O)c2cccc(C(=O)O)n2)c(F)c1
1920337,CHEMBL906,289.32,-1.59,ACID,Nc1cc(N2CCCCC2)nc(N)[n+]1OS(=O)(=O)[O-]

In [ ]:
df2 = df[['ChEMBLID', 'Smiles', 'MolecularSpecies', 'MolecularWeight', 'AlogP' ]]
df2

,ChEMBLID,Smiles,MolecularSpecies,MolecularWeight,AlogP
0,CHEMBL3425773,N#Cc1ccc(-c2coc3cc(O)ccc3c2=O)cc1,ACID,263.25,3.04
1,CHEMBL1998753,COC(=O)[C@@H]1[C@H]2[C@H](OC(=O)c3ccccc3)CCN2O...,NEUTRAL,455.46,2.28
2,CHEMBL1867860,COc1cccc(-n2c(=O)c3c(C)c(C)sc3n(CC(=O)Nc3ccccc...,NEUTRAL,465.53,3.49
3,CHEMBL481686,Cc1cc(C)cc(N(Cc2ccc(CO)cc2)c2cc(C(=O)N3CCCC3)n...,NEUTRAL,417.55,4.71
4,CHEMBL1939547,O=[N+]([O-])c1ccc(-c2nsc(-c3ccc([N+](=O)[O-])c...,NEUTRAL,328.31,3.69
...,...,...,...,...,...
1920333,CHEMBL1627004,CC(C)C[C@H](NC(=O)[C@H](CC(=O)OS(=O)(=O)[O-])N...,None,1815.46,NaN
1920334,CHEMBL3958686,Cc1c(Cc2ccc(OC(C)C)cc2)c(O[C@@H]2O[C@H](CO)[C@...,NEUTRAL,450.53,1.33
1920335,CHEMBL1201377,CCCCC(C)(O)C/C=C/[C@H]1[C@H](O)CC(=O)[C@@H]1CC...,ACID,368.51,3.87
1920336,CHEMBL537710,Cl.NS(=O)(=O)c1ccc(NC(=O)c2cccc(C(=O)O)n2)c(F)c1,ACID,375.76,0.82
1920337,CHEMBL906,Nc1cc(N2CCCCC2)nc(N)[n+]1OS(=O)(=O)[O-],ACID,289.32,-1.59

In [ ]:
df2.isnull().sum()

ChEMBLID                0
Smiles               5486
MolecularSpecies     2085
MolecularWeight      2085
AlogP               33904
dtype: int64

In [ ]:
df3 = df2.dropna(subset=['Smiles'])
df3

,ChEMBLID,Smiles,MolecularSpecies,MolecularWeight,AlogP
0,CHEMBL3425773,N#Cc1ccc(-c2coc3cc(O)ccc3c2=O)cc1,ACID,263.25,3.04
1,CHEMBL1998753,COC(=O)[C@@H]1[C@H]2[C@H](OC(=O)c3ccccc3)CCN2O...,NEUTRAL,455.46,2.28
2,CHEMBL1867860,COc1cccc(-n2c(=O)c3c(C)c(C)sc3n(CC(=O)Nc3ccccc...,NEUTRAL,465.53,3.49
3,CHEMBL481686,Cc1cc(C)cc(N(Cc2ccc(CO)cc2)c2cc(C(=O)N3CCCC3)n...,NEUTRAL,417.55,4.71
4,CHEMBL1939547,O=[N+]([O-])c1ccc(-c2nsc(-c3ccc([N+](=O)[O-])c...,NEUTRAL,328.31,3.69
...,...,...,...,...,...
1920333,CHEMBL1627004,CC(C)C[C@H](NC(=O)[C@H](CC(=O)OS(=O)(=O)[O-])N...,None,1815.46,NaN
1920334,CHEMBL3958686,Cc1c(Cc2ccc(OC(C)C)cc2)c(O[C@@H]2O[C@H](CO)[C@...,NEUTRAL,450.53,1.33
1920335,CHEMBL1201377,CCCCC(C)(O)C/C=C/[C@H]1[C@H](O)CC(=O)[C@@H]1CC...,ACID,368.51,3.87
1920336,CHEMBL537710,Cl.NS(=O)(=O)c1ccc(NC(=O)c2cccc(C(=O)O)n2)c(F)c1,ACID,375.76,0.82
1920337,CHEMBL906,Nc1cc(N2CCCCC2)nc(N)[n+]1OS(=O)(=O)[O-],ACID,289.32,-1.59

In [ ]:
dropped_rows = df2[~df2.index.isin(df3.index)]
dropped_rows

              ChEMBLID Smiles MolecularSpecies  MolecularWeight  AlogP
260      CHEMBL3526843    NaN              NaN              NaN    NaN
3158     CHEMBL2068293    NaN             None           650.15    NaN
3306      CHEMBL164788    NaN             None           550.34    NaN
3650     CHEMBL3348867    NaN              NaN              NaN    NaN
4165      CHEMBL420188    NaN             None           392.18    NaN
...                ...    ...              ...              ...    ...
1919880  CHEMBL3545180    NaN              NaN              NaN    NaN
1919886  CHEMBL1909055    NaN             None           129.84    NaN
1919985  CHEMBL2104381    NaN             None          1355.40    NaN
1919986  CHEMBL2096655    NaN             None          1354.40    NaN
1920189  CHEMBL4071680    NaN             None           907.88    NaN

[5486 rows x 5 columns]

In [ ]:
df3.Smiles.value_counts()

Oc1cccc(-c2c3nc(c(-c4cccc(O)c4)c4ccc([nH]4)c(-c4cccc(O)c4)c4nc(c(-c5cccc(O)c5)c5ccc2[nH]5)CC4)C=C3)c1    3
COc1ccc2c(c1)c(OC(C)C)c(C(N)=O)[s+]2[O-]                                                                 3
CC(=O)C=C=C1C(C)(C)C[C@H](O)C[C@@]1(C)O                                                                  3
C=CC1=C(C)c2cc3[nH]c(cc4nc(cc5[nH]c(cc1n2)c(C)c5C=C)C(C)=C4CCC(=O)O)c(CCC(=O)O)c3C                       2
CCC1(O)[C@H](O)CC(=C/C=C2/CCC[C@@]3(C)[C@H]2CC[C@@H]3[C@H](C)CCCC(C)(C)O)C[C@H]1O                        2
                                                                                                        ..
C[C@H](NC(=O)CC#N)c1ccc(CN2Cc3ccc(OCC4CC4)cc3[C@H](F)C2)cc1                                              1
CCNC(=S)N/N=C1\C(=O)N(CN2CCOCC2)c2ccc(F)cc21                                                             1
CC(=O)Nc1ccc(OC(C)(C)C)cc1                                                                               1
FC(F)(F)c1ccccc1CN(CC1CC1)C1CCNCC1                                                                       1
Nc1cc(N2CCCCC2)nc(N)[n+]1OS(=O)(=O)[O-]                                                                  1
Name: Smiles, Length: 1914740, dtype: int64

In [ ]:
df3.duplicated(subset='Smiles')             # keep: {'first', 'last', False}, default 'first'

0          False
1          False
2          False
3          False
4          False
           ...
1920333    False
1920334    False
1920335    False
1920336    False
1920337    False
Length: 1914852, dtype: bool

In [ ]:
df3.Smiles.duplicated()

0          False
1          False
2          False
3          False
4          False
           ...
1920333    False
1920334    False
1920335    False
1920336    False
1920337    False
Name: Smiles, Length: 1914852, dtype: bool

In [ ]:
df3.Smiles.duplicated().sum()

112

In [ ]:
df3.duplicated(subset=['Smiles', 'MolecularSpecies'])

## Method 1

In [ ]:
duplicated_smiles = df3[df3.duplicated(subset=['Smiles'])]
duplicated_smiles

,ChEMBLID,Smiles,MolecularSpecies,MolecularWeight,AlogP
109366,CHEMBL3960398,CC(C)(NS(=O)(=O)c1cc(F)cc(F)c1)C(=O)NC1C2CC3CC...,NEUTRAL,455.53,1.82
205487,CHEMBL2027887,CCNC(=O)[C@@]1(c2ccccc2)CC1CN,BASE,218.30,1.04
279974,CHEMBL4113560,CC1=C[C@@H]2Cc3nc4cc(Cl)ccc4c(NCCCCCCCCCNC(=O)...,NEUTRAL,692.26,8.64
306872,CHEMBL3084963,CC1[C@H](O)CC(=C/C=C2\CCC[C@@]3(C)[C@H]2CC[C@@...,NEUTRAL,418.66,5.78
364980,CHEMBL117908,c1cc2cc(c1)C[n+]1ccc(c3ccccc31)NCc1ccc(cc1)CNc...,NEUTRAL,494.64,6.20
...,...,...,...,...,...
1889398,CHEMBL3084986,COCC1(O)[C@H](O)CC(=C/C=C2/CCC[C@@]3(C)[C@H]2C...,NEUTRAL,464.69,4.53
1900078,CHEMBL2021485,CCCOC1[C@H](O)CC(=C/C=C2\CCC[C@]3(C)C(C(C)SCCC...,NEUTRAL,506.79,6.35
1908623,CHEMBL186139,c1ccc2c(c1)c1cc[n+]2CCCCCC[n+]2ccc(c3ccccc32)N...,NEUTRAL,454.66,6.23
1919665,CHEMBL42743,CC[C@H]1OC(=O)C[C@@H](O)[C@H](C)[C@@H](O[C@@H]...,NEUTRAL,916.11,1.83
1920210,CHEMBL185463,c1ccc2c(c1)c1cc[n+]2CCCCC[n+]2ccc(c3ccccc32)NC...,NEUTRAL,426.61,5.45

In [ ]:
duplicated_smiles = df3[df3.duplicated(subset=['Smiles'], keep=False)]
duplicated_smiles

,ChEMBLID,Smiles,MolecularSpecies,MolecularWeight,AlogP
9748,CHEMBL519462,O=C1C(O)=C(C2CCC(c3ccc(Cl)cc3)CC2)C(=O)c2ccccc21,ACID,366.84,5.51
15698,CHEMBL4226596,C=C1C(=O)O[C@H]2[C@H]1CC/C(CO)=C/CC[C@@]1(C)O[...,NEUTRAL,264.32,1.73
49722,CHEMBL514116,CCC(O)(CC)CS[C@H](C)C1=CC[C@H]2/C(=C/C=C3C[C@@...,NEUTRAL,494.74,4.54
69285,CHEMBL226380,C[C@@H](CCCC(C)(C)O)C1CCC2/C(=C/C=C3C[C@@H](O)...,NEUTRAL,448.66,6.04
70452,CHEMBL3608402,CC(C)(NS(=O)(=O)c1cc(F)cc(F)c1)C(=O)NC1C2CC3CC...,NEUTRAL,455.53,1.82
...,...,...,...,...,...
1889398,CHEMBL3084986,COCC1(O)[C@H](O)CC(=C/C=C2/CCC[C@@]3(C)[C@H]2C...,NEUTRAL,464.69,4.53
1900078,CHEMBL2021485,CCCOC1[C@H](O)CC(=C/C=C2\CCC[C@]3(C)C(C(C)SCCC...,NEUTRAL,506.79,6.35
1908623,CHEMBL186139,c1ccc2c(c1)c1cc[n+]2CCCCCC[n+]2ccc(c3ccccc32)N...,NEUTRAL,454.66,6.23
1919665,CHEMBL42743,CC[C@H]1OC(=O)C[C@@H](O)[C@H](C)[C@@H](O[C@@H]...,NEUTRAL,916.11,1.83
1920210,CHEMBL185463,c1ccc2c(c1)c1cc[n+]2CCCCC[n+]2ccc(c3ccccc32)NC...,NEUTRAL,426.61,5.45

In [ ]:
duplicated_smiles = df3[df3.duplicated(subset=['Smiles'], keep=False)].sort_values('Smiles')
duplicated_smiles

,ChEMBLID,Smiles,MolecularSpecies,MolecularWeight,AlogP
1090635,CHEMBL4170041,C/C1=C/C(=O)O[C@H](C(C)(C)C)CCC[C@H](O)CCC[C@H...,NEUTRAL,789.14,6.29
481873,CHEMBL4166627,C/C1=C/C(=O)O[C@H](C(C)(C)C)CCC[C@H](O)CCC[C@H...,NEUTRAL,789.14,6.29
995629,CHEMBL25422,C1=CC(=Nn2cccc2)C=CC1=Nn1cccc1,BASE,236.28,2.52
742951,CHEMBL25024,C1=CC(=Nn2cccc2)C=CC1=Nn1cccc1,BASE,236.28,2.52
447200,CHEMBL2373168,C1=Cc2nc1c(-c1ccccc1)c1ccc([n-]1)c(-c1ccccc1)c...,NEUTRAL,678.13,11.32
...,...,...,...,...,...
1237704,CHEMBL1180158,c1ccc2c(c1)c1cc[n+]2CCCCCC[n+]2ccc(c3ccccc32)N...,NEUTRAL,454.66,6.23
1758731,CHEMBL1185552,c1ccc2c(c1)c1cc[n+]2CCCCC[n+]2ccc(c3ccccc32)NC...,NEUTRAL,426.61,5.45
1920210,CHEMBL185463,c1ccc2c(c1)c1cc[n+]2CCCCC[n+]2ccc(c3ccccc32)NC...,NEUTRAL,426.61,5.45
1864807,CHEMBL430146,c1ccc2c(c1)c1cc[n+]2Cc2ccc(cc2)C[n+]2ccc(c3ccc...,NEUTRAL,494.64,6.20
213922,CHEMBL4292329,c1ccc2c(c1)c1cc[n+]2Cc2ccc(cc2)C[n+]2ccc(c3ccc...,NEUTRAL,494.64,6.20

In [ ]:
df.loc[1237704]['Smiles']

'c1ccc2c(c1)c1cc[n+]2CCCCCC[n+]2ccc(c3ccccc32)NCCCCCCN1'

In [ ]:
df.loc[1758731]['Smiles']

In [ ]:
df.loc[1920210]['Smiles']

In [ ]:
duplicated_smiles

In [ ]:
df.loc[1908623]['Smiles']

## Method 2

In [ ]:
df4 = df3.drop_duplicates('Smiles')
df4

,ChEMBLID,Smiles,MolecularSpecies,MolecularWeight,AlogP
0,CHEMBL3425773,N#Cc1ccc(-c2coc3cc(O)ccc3c2=O)cc1,ACID,263.25,3.04
1,CHEMBL1998753,COC(=O)[C@@H]1[C@H]2[C@H](OC(=O)c3ccccc3)CCN2O...,NEUTRAL,455.46,2.28
2,CHEMBL1867860,COc1cccc(-n2c(=O)c3c(C)c(C)sc3n(CC(=O)Nc3ccccc...,NEUTRAL,465.53,3.49
3,CHEMBL481686,Cc1cc(C)cc(N(Cc2ccc(CO)cc2)c2cc(C(=O)N3CCCC3)n...,NEUTRAL,417.55,4.71
4,CHEMBL1939547,O=[N+]([O-])c1ccc(-c2nsc(-c3ccc([N+](=O)[O-])c...,NEUTRAL,328.31,3.69
...,...,...,...,...,...
1920333,CHEMBL1627004,CC(C)C[C@H](NC(=O)[C@H](CC(=O)OS(=O)(=O)[O-])N...,None,1815.46,NaN
1920334,CHEMBL3958686,Cc1c(Cc2ccc(OC(C)C)cc2)c(O[C@@H]2O[C@H](CO)[C@...,NEUTRAL,450.53,1.33
1920335,CHEMBL1201377,CCCCC(C)(O)C/C=C/[C@H]1[C@H](O)CC(=O)[C@@H]1CC...,ACID,368.51,3.87
1920336,CHEMBL537710,Cl.NS(=O)(=O)c1ccc(NC(=O)c2cccc(C(=O)O)n2)c(F)c1,ACID,375.76,0.82
1920337,CHEMBL906,Nc1cc(N2CCCCC2)nc(N)[n+]1OS(=O)(=O)[O-],ACID,289.32,-1.59

In [ ]:
dropped_rows = df3[~df3.index.isin(df4.index)]
dropped_rows

,ChEMBLID,Smiles,MolecularSpecies,MolecularWeight,AlogP
109366,CHEMBL3960398,CC(C)(NS(=O)(=O)c1cc(F)cc(F)c1)C(=O)NC1C2CC3CC...,NEUTRAL,455.53,1.82
205487,CHEMBL2027887,CCNC(=O)[C@@]1(c2ccccc2)CC1CN,BASE,218.30,1.04
279974,CHEMBL4113560,CC1=C[C@@H]2Cc3nc4cc(Cl)ccc4c(NCCCCCCCCCNC(=O)...,NEUTRAL,692.26,8.64
306872,CHEMBL3084963,CC1[C@H](O)CC(=C/C=C2\CCC[C@@]3(C)[C@H]2CC[C@@...,NEUTRAL,418.66,5.78
364980,CHEMBL117908,c1cc2cc(c1)C[n+]1ccc(c3ccccc31)NCc1ccc(cc1)CNc...,NEUTRAL,494.64,6.20
...,...,...,...,...,...
1889398,CHEMBL3084986,COCC1(O)[C@H](O)CC(=C/C=C2/CCC[C@@]3(C)[C@H]2C...,NEUTRAL,464.69,4.53
1900078,CHEMBL2021485,CCCOC1[C@H](O)CC(=C/C=C2\CCC[C@]3(C)C(C(C)SCCC...,NEUTRAL,506.79,6.35
1908623,CHEMBL186139,c1ccc2c(c1)c1cc[n+]2CCCCCC[n+]2ccc(c3ccccc32)N...,NEUTRAL,454.66,6.23
1919665,CHEMBL42743,CC[C@H]1OC(=O)C[C@@H](O)[C@H](C)[C@@H](O[C@@H]...,NEUTRAL,916.11,1.83
1920210,CHEMBL185463,c1ccc2c(c1)c1cc[n+]2CCCCC[n+]2ccc(c3ccccc32)NC...,NEUTRAL,426.61,5.45

In [ ]:
duplicated_smiles = pd.concat([df4.loc[df4.Smiles.isin(dropped_rows.Smiles), :], dropped_rows]).sort_values('Smiles')
duplicated_smiles

,ChEMBLID,Smiles,MolecularSpecies,MolecularWeight,AlogP
481873,CHEMBL4166627,C/C1=C/C(=O)O[C@H](C(C)(C)C)CCC[C@H](O)CCC[C@H...,NEUTRAL,789.14,6.29
1090635,CHEMBL4170041,C/C1=C/C(=O)O[C@H](C(C)(C)C)CCC[C@H](O)CCC[C@H...,NEUTRAL,789.14,6.29
742951,CHEMBL25024,C1=CC(=Nn2cccc2)C=CC1=Nn1cccc1,BASE,236.28,2.52
995629,CHEMBL25422,C1=CC(=Nn2cccc2)C=CC1=Nn1cccc1,BASE,236.28,2.52
447200,CHEMBL2373168,C1=Cc2nc1c(-c1ccccc1)c1ccc([n-]1)c(-c1ccccc1)c...,NEUTRAL,678.13,11.32
...,...,...,...,...,...
1237704,CHEMBL1180158,c1ccc2c(c1)c1cc[n+]2CCCCCC[n+]2ccc(c3ccccc32)N...,NEUTRAL,454.66,6.23
1920210,CHEMBL185463,c1ccc2c(c1)c1cc[n+]2CCCCC[n+]2ccc(c3ccccc32)NC...,NEUTRAL,426.61,5.45
1758731,CHEMBL1185552,c1ccc2c(c1)c1cc[n+]2CCCCC[n+]2ccc(c3ccccc32)NC...,NEUTRAL,426.61,5.45
213922,CHEMBL4292329,c1ccc2c(c1)c1cc[n+]2Cc2ccc(cc2)C[n+]2ccc(c3ccc...,NEUTRAL,494.64,6.20
1864807,CHEMBL430146,c1ccc2c(c1)c1cc[n+]2Cc2ccc(cc2)C[n+]2ccc(c3ccc...,NEUTRAL,494.64,6.20

In [ ]:
df3.duplicated(subset='AlogP')

0          False
1          False
2          False
3          False
4          False
           ...
1920333     True
1920334     True
1920335     True
1920336     True
1920337     True
Length: 1914852, dtype: bool

In [ ]:
df3.to_csv('Chembl_library_2M_3.csv', index=False)