In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Chembl_library_2M_2.csv')
df.head()

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (27) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,ChEMBLID,Name,Synonyms,Type,MaxPhase,MolecularWeight,Targets,Bioactivities,AlogP,PolarSurfaceArea,...,InorganicFlag,HeavyAtoms,HBA(Lipinski),HBD(Lipinski),#RO5Violations(Lipinski),MolecularWeight(Monoisotopic),MolecularSpecies,MolecularFormula,Smiles,InchiKey
0,CHEMBL3425773,NaN,NaN,Small molecule,0,263.25,1.0,1.0,3.04,74.23,...,-1,20,4,1,0,263.0582,ACID,C16H9NO3,N#Cc1ccc(-c2coc3cc(O)ccc3c2=O)cc1,VFISVTBQGUQPIQ-UHFFFAOYSA-N
1,CHEMBL1998753,NaN,NaN,Small molecule,0,455.46,56.0,56.0,2.28,100.60,...,-1,33,9,0,0,455.158,NEUTRAL,C24H25NO8,COC(=O)[C@@H]1[C@H]2[C@H](OC(=O)c3ccccc3)CCN2O...,OQFYYDNHLYZLOL-BORCDFBASA-N
2,CHEMBL1867860,NaN,NaN,Small molecule,0,465.53,4.0,4.0,3.49,91.56,...,-1,33,8,1,0,465.1358,NEUTRAL,C24H23N3O5S,COc1cccc(-n2c(=O)c3c(C)c(C)sc3n(CC(=O)Nc3ccccc...,CHCLAAKAFOYXSQ-UHFFFAOYSA-N
3,CHEMBL481686,NaN,NaN,Small molecule,0,417.55,1.0,2.0,4.71,48.71,...,-1,31,5,1,0,417.2416,NEUTRAL,C26H31N3O2,Cc1cc(C)cc(N(Cc2ccc(CO)cc2)c2cc(C(=O)N3CCCC3)n...,UFQDWXYZGWHYFO-UHFFFAOYSA-N
4,CHEMBL1939547,NaN,NaN,Small molecule,0,328.31,5.0,10.0,3.69,112.06,...,-1,23,8,0,0,328.0266,NEUTRAL,C14H8N4O4S,O=[N+]([O-])c1ccc(-c2nsc(-c3ccc([N+](=O)[O-])c...,VCXUCYVZJDYDCE-UHFFFAOYSA-N

In [ ]:
df2 = df[['ChEMBLID', 'MolecularWeight','AlogP', 'MolecularSpecies', 'Smiles']]
df2

,ChEMBLID,MolecularWeight,AlogP,MolecularSpecies,Smiles
0,CHEMBL3425773,263.25,3.04,ACID,N#Cc1ccc(-c2coc3cc(O)ccc3c2=O)cc1
1,CHEMBL1998753,455.46,2.28,NEUTRAL,COC(=O)[C@@H]1[C@H]2[C@H](OC(=O)c3ccccc3)CCN2O...
2,CHEMBL1867860,465.53,3.49,NEUTRAL,COc1cccc(-n2c(=O)c3c(C)c(C)sc3n(CC(=O)Nc3ccccc...
3,CHEMBL481686,417.55,4.71,NEUTRAL,Cc1cc(C)cc(N(Cc2ccc(CO)cc2)c2cc(C(=O)N3CCCC3)n...
4,CHEMBL1939547,328.31,3.69,NEUTRAL,O=[N+]([O-])c1ccc(-c2nsc(-c3ccc([N+](=O)[O-])c...
...,...,...,...,...,...
1920333,CHEMBL1627004,1815.46,NaN,None,CC(C)C[C@H](NC(=O)[C@H](CC(=O)OS(=O)(=O)[O-])N...
1920334,CHEMBL3958686,450.53,1.33,NEUTRAL,Cc1c(Cc2ccc(OC(C)C)cc2)c(O[C@@H]2O[C@H](CO)[C@...
1920335,CHEMBL1201377,368.51,3.87,ACID,CCCCC(C)(O)C/C=C/[C@H]1[C@H](O)CC(=O)[C@@H]1CC...
1920336,CHEMBL537710,375.76,0.82,ACID,Cl.NS(=O)(=O)c1ccc(NC(=O)c2cccc(C(=O)O)n2)c(F)c1
1920337,CHEMBL906,289.32,-1.59,ACID,Nc1cc(N2CCCCC2)nc(N)[n+]1OS(=O)(=O)[O-]

In [ ]:
df2 = df[['ChEMBLID', 'Smiles', 'MolecularSpecies', 'MolecularWeight', 'AlogP' ]]
df2

,ChEMBLID,Smiles,MolecularSpecies,MolecularWeight,AlogP
0,CHEMBL3425773,N#Cc1ccc(-c2coc3cc(O)ccc3c2=O)cc1,ACID,263.25,3.04
1,CHEMBL1998753,COC(=O)[C@@H]1[C@H]2[C@H](OC(=O)c3ccccc3)CCN2O...,NEUTRAL,455.46,2.28
2,CHEMBL1867860,COc1cccc(-n2c(=O)c3c(C)c(C)sc3n(CC(=O)Nc3ccccc...,NEUTRAL,465.53,3.49
3,CHEMBL481686,Cc1cc(C)cc(N(Cc2ccc(CO)cc2)c2cc(C(=O)N3CCCC3)n...,NEUTRAL,417.55,4.71
4,CHEMBL1939547,O=[N+]([O-])c1ccc(-c2nsc(-c3ccc([N+](=O)[O-])c...,NEUTRAL,328.31,3.69
...,...,...,...,...,...
1920333,CHEMBL1627004,CC(C)C[C@H](NC(=O)[C@H](CC(=O)OS(=O)(=O)[O-])N...,None,1815.46,NaN
1920334,CHEMBL3958686,Cc1c(Cc2ccc(OC(C)C)cc2)c(O[C@@H]2O[C@H](CO)[C@...,NEUTRAL,450.53,1.33
1920335,CHEMBL1201377,CCCCC(C)(O)C/C=C/[C@H]1[C@H](O)CC(=O)[C@@H]1CC...,ACID,368.51,3.87
1920336,CHEMBL537710,Cl.NS(=O)(=O)c1ccc(NC(=O)c2cccc(C(=O)O)n2)c(F)c1,ACID,375.76,0.82
1920337,CHEMBL906,Nc1cc(N2CCCCC2)nc(N)[n+]1OS(=O)(=O)[O-],ACID,289.32,-1.59

In [ ]:
df2.isnull().sum()

ChEMBLID                0
Smiles               5486
MolecularSpecies     2085
MolecularWeight      2085
AlogP               33904
dtype: int64

In [ ]:
df3 = df2.dropna(subset=['Smiles'])
df3

,ChEMBLID,Smiles,MolecularSpecies,MolecularWeight,AlogP
0,CHEMBL3425773,N#Cc1ccc(-c2coc3cc(O)ccc3c2=O)cc1,ACID,263.25,3.04
1,CHEMBL1998753,COC(=O)[C@@H]1[C@H]2[C@H](OC(=O)c3ccccc3)CCN2O...,NEUTRAL,455.46,2.28
2,CHEMBL1867860,COc1cccc(-n2c(=O)c3c(C)c(C)sc3n(CC(=O)Nc3ccccc...,NEUTRAL,465.53,3.49
3,CHEMBL481686,Cc1cc(C)cc(N(Cc2ccc(CO)cc2)c2cc(C(=O)N3CCCC3)n...,NEUTRAL,417.55,4.71
4,CHEMBL1939547,O=[N+]([O-])c1ccc(-c2nsc(-c3ccc([N+](=O)[O-])c...,NEUTRAL,328.31,3.69
...,...,...,...,...,...
1920333,CHEMBL1627004,CC(C)C[C@H](NC(=O)[C@H](CC(=O)OS(=O)(=O)[O-])N...,None,1815.46,NaN
1920334,CHEMBL3958686,Cc1c(Cc2ccc(OC(C)C)cc2)c(O[C@@H]2O[C@H](CO)[C@...,NEUTRAL,450.53,1.33
1920335,CHEMBL1201377,CCCCC(C)(O)C/C=C/[C@H]1[C@H](O)CC(=O)[C@@H]1CC...,ACID,368.51,3.87
1920336,CHEMBL537710,Cl.NS(=O)(=O)c1ccc(NC(=O)c2cccc(C(=O)O)n2)c(F)c1,ACID,375.76,0.82
1920337,CHEMBL906,Nc1cc(N2CCCCC2)nc(N)[n+]1OS(=O)(=O)[O-],ACID,289.32,-1.59

In [ ]:
df3.Smiles.value_counts()

Oc1cccc(-c2c3nc(c(-c4cccc(O)c4)c4ccc([nH]4)c(-c4cccc(O)c4)c4nc(c(-c5cccc(O)c5)c5ccc2[nH]5)CC4)C=C3)c1    3
COc1ccc2c(c1)c(OC(C)C)c(C(N)=O)[s+]2[O-]                                                                 3
CC(=O)C=C=C1C(C)(C)C[C@H](O)C[C@@]1(C)O                                                                  3
C=CC1=C(C)c2cc3[nH]c(cc4nc(cc5[nH]c(cc1n2)c(C)c5C=C)C(C)=C4CCC(=O)O)c(CCC(=O)O)c3C                       2
CCC1(O)[C@H](O)CC(=C/C=C2/CCC[C@@]3(C)[C@H]2CC[C@@H]3[C@H](C)CCCC(C)(C)O)C[C@H]1O                        2
                                                                                                        ..
C[C@H](NC(=O)CC#N)c1ccc(CN2Cc3ccc(OCC4CC4)cc3[C@H](F)C2)cc1                                              1
CCNC(=S)N/N=C1\C(=O)N(CN2CCOCC2)c2ccc(F)cc21                                                             1
CC(=O)Nc1ccc(OC(C)(C)C)cc1                                                                               1
FC(F)(F)c1ccccc1CN(CC1CC1)C1CCNCC1                                                                       1
Nc1cc(N2CCCCC2)nc(N)[n+]1OS(=O)(=O)[O-]                                                                  1
Name: Smiles, Length: 1914740, dtype: int64

In [ ]:
df4 = df3.drop_duplicates('Smiles')
df4

,ChEMBLID,Smiles,MolecularSpecies,MolecularWeight,AlogP
0,CHEMBL3425773,N#Cc1ccc(-c2coc3cc(O)ccc3c2=O)cc1,ACID,263.25,3.04
1,CHEMBL1998753,COC(=O)[C@@H]1[C@H]2[C@H](OC(=O)c3ccccc3)CCN2O...,NEUTRAL,455.46,2.28
2,CHEMBL1867860,COc1cccc(-n2c(=O)c3c(C)c(C)sc3n(CC(=O)Nc3ccccc...,NEUTRAL,465.53,3.49
3,CHEMBL481686,Cc1cc(C)cc(N(Cc2ccc(CO)cc2)c2cc(C(=O)N3CCCC3)n...,NEUTRAL,417.55,4.71
4,CHEMBL1939547,O=[N+]([O-])c1ccc(-c2nsc(-c3ccc([N+](=O)[O-])c...,NEUTRAL,328.31,3.69
...,...,...,...,...,...
1920333,CHEMBL1627004,CC(C)C[C@H](NC(=O)[C@H](CC(=O)OS(=O)(=O)[O-])N...,None,1815.46,NaN
1920334,CHEMBL3958686,Cc1c(Cc2ccc(OC(C)C)cc2)c(O[C@@H]2O[C@H](CO)[C@...,NEUTRAL,450.53,1.33
1920335,CHEMBL1201377,CCCCC(C)(O)C/C=C/[C@H]1[C@H](O)CC(=O)[C@@H]1CC...,ACID,368.51,3.87
1920336,CHEMBL537710,Cl.NS(=O)(=O)c1ccc(NC(=O)c2cccc(C(=O)O)n2)c(F)c1,ACID,375.76,0.82
1920337,CHEMBL906,Nc1cc(N2CCCCC2)nc(N)[n+]1OS(=O)(=O)[O-],ACID,289.32,-1.59

In [ ]:
df5 = df4.rename(columns={'ChEMBLID':'ID', 'MolecularWeight':'MW'})
df5

,ID,Smiles,MolecularSpecies,MW,AlogP
0,CHEMBL3425773,N#Cc1ccc(-c2coc3cc(O)ccc3c2=O)cc1,ACID,263.25,3.04
1,CHEMBL1998753,COC(=O)[C@@H]1[C@H]2[C@H](OC(=O)c3ccccc3)CCN2O...,NEUTRAL,455.46,2.28
2,CHEMBL1867860,COc1cccc(-n2c(=O)c3c(C)c(C)sc3n(CC(=O)Nc3ccccc...,NEUTRAL,465.53,3.49
3,CHEMBL481686,Cc1cc(C)cc(N(Cc2ccc(CO)cc2)c2cc(C(=O)N3CCCC3)n...,NEUTRAL,417.55,4.71
4,CHEMBL1939547,O=[N+]([O-])c1ccc(-c2nsc(-c3ccc([N+](=O)[O-])c...,NEUTRAL,328.31,3.69
...,...,...,...,...,...
1920333,CHEMBL1627004,CC(C)C[C@H](NC(=O)[C@H](CC(=O)OS(=O)(=O)[O-])N...,None,1815.46,NaN
1920334,CHEMBL3958686,Cc1c(Cc2ccc(OC(C)C)cc2)c(O[C@@H]2O[C@H](CO)[C@...,NEUTRAL,450.53,1.33
1920335,CHEMBL1201377,CCCCC(C)(O)C/C=C/[C@H]1[C@H](O)CC(=O)[C@@H]1CC...,ACID,368.51,3.87
1920336,CHEMBL537710,Cl.NS(=O)(=O)c1ccc(NC(=O)c2cccc(C(=O)O)n2)c(F)c1,ACID,375.76,0.82
1920337,CHEMBL906,Nc1cc(N2CCCCC2)nc(N)[n+]1OS(=O)(=O)[O-],ACID,289.32,-1.59

In [ ]:
df5.to_csv('Chembl_library_2M_3.csv', index=False)