In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Chembl_library_2M.csv', sep=';')
df.head()

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (27) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,ChEMBL ID,Name,Synonyms,Type,Max Phase,Molecular Weight,Targets,Bioactivities,AlogP,Polar Surface Area,...,Inorganic Flag,Heavy Atoms,HBA (Lipinski),HBD (Lipinski),#RO5 Violations (Lipinski),Molecular Weight (Monoisotopic),Molecular Species,Molecular Formula,Smiles,Inchi Key
0,CHEMBL3425773,NaN,NaN,Small molecule,0,263.25,1.0,1.0,3.04,74.23,...,-1,20,4,1,0,263.0582,ACID,C16H9NO3,N#Cc1ccc(-c2coc3cc(O)ccc3c2=O)cc1,VFISVTBQGUQPIQ-UHFFFAOYSA-N
1,CHEMBL1998753,NaN,NaN,Small molecule,0,455.46,56.0,56.0,2.28,100.60,...,-1,33,9,0,0,455.158,NEUTRAL,C24H25NO8,COC(=O)[C@@H]1[C@H]2[C@H](OC(=O)c3ccccc3)CCN2O...,OQFYYDNHLYZLOL-BORCDFBASA-N
2,CHEMBL1867860,NaN,NaN,Small molecule,0,465.53,4.0,4.0,3.49,91.56,...,-1,33,8,1,0,465.1358,NEUTRAL,C24H23N3O5S,COc1cccc(-n2c(=O)c3c(C)c(C)sc3n(CC(=O)Nc3ccccc...,CHCLAAKAFOYXSQ-UHFFFAOYSA-N
3,CHEMBL481686,NaN,NaN,Small molecule,0,417.55,1.0,2.0,4.71,48.71,...,-1,31,5,1,0,417.2416,NEUTRAL,C26H31N3O2,Cc1cc(C)cc(N(Cc2ccc(CO)cc2)c2cc(C(=O)N3CCCC3)n...,UFQDWXYZGWHYFO-UHFFFAOYSA-N
4,CHEMBL1939547,NaN,NaN,Small molecule,0,328.31,5.0,10.0,3.69,112.06,...,-1,23,8,0,0,328.0266,NEUTRAL,C14H8N4O4S,O=[N+]([O-])c1ccc(-c2nsc(-c3ccc([N+](=O)[O-])c...,VCXUCYVZJDYDCE-UHFFFAOYSA-N

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1920338 entries, 0 to 1920337
Data columns (total 32 columns):
 #   Column                           Dtype
---  ------                           -----
 0   ChEMBL ID                        object
 1   Name                             object
 2   Synonyms                         object
 3   Type                             object
 4   Max Phase                        int64
 5   Molecular Weight                 float64
 6   Targets                          float64
 7   Bioactivities                    float64
 8   AlogP                            object
 9   Polar Surface Area               object
 10  HBA                              object
 11  HBD                              object
 12  #RO5 Violations                  object
 13  #Rotatable Bonds                 object
 14  Passes Ro3                       object
 15  QED Weighted                     object
 16  CX Acidic pKa                    object
 17  CX Basic pKa                     object
 18  CX LogP                          object
 19  CX LogD                          object
 20  Aromatic Rings                   object
 21  Structure Type                   object
 22  Inorganic Flag                   int64
 23  Heavy Atoms                      object
 24  HBA (Lipinski)                   object
 25  HBD (Lipinski)                   object
 26  #RO5 Violations (Lipinski)       object
 27  Molecular Weight (Monoisotopic)  object
 28  Molecular Species                object
 29  Molecular Formula                object
 30  Smiles                           object
 31  Inchi Key                        object
dtypes: float64(3), int64(2), object(27)
memory usage: 468.8+ MB

In [ ]:
df.dtypes

ChEMBL ID                           object
Name                                object
Synonyms                            object
Type                                object
Max Phase                            int64
Molecular Weight                   float64
Targets                            float64
Bioactivities                      float64
AlogP                               object
Polar Surface Area                  object
HBA                                 object
HBD                                 object
#RO5 Violations                     object
#Rotatable Bonds                    object
Passes Ro3                          object
QED Weighted                        object
CX Acidic pKa                       object
CX Basic pKa                        object
CX LogP                             object
CX LogD                             object
Aromatic Rings                      object
Structure Type                      object
Inorganic Flag                       int64
Heavy Atoms                         object
HBA (Lipinski)                      object
HBD (Lipinski)                      object
#RO5 Violations (Lipinski)          object
Molecular Weight (Monoisotopic)     object
Molecular Species                   object
Molecular Formula                   object
Smiles                              object
Inchi Key                           object
dtype: object

In [ ]:
df.AlogP.dtype

dtype('O')

In [ ]:
df.select_dtypes(include='number')

         Max Phase  Molecular Weight  Targets  Bioactivities  Inorganic Flag
0                0            263.25      1.0            1.0              -1
1                0            455.46     56.0           56.0              -1
2                0            465.53      4.0            4.0              -1
3                0            417.55      1.0            2.0              -1
4                0            328.31      5.0           10.0              -1
...            ...               ...      ...            ...             ...
1920333          0           1815.46      2.0            8.0              -1
1920334          0            450.53      4.0           11.0               0
1920335          0            368.51      NaN            NaN               0
1920336          0            375.76      1.0            4.0              -1
1920337          0            289.32      3.0            4.0               0

[1920338 rows x 5 columns]

In [ ]:
df.select_dtypes(exclude='object')

         Max Phase  Molecular Weight  Targets  Bioactivities  Inorganic Flag
0                0            263.25      1.0            1.0              -1
1                0            455.46     56.0           56.0              -1
2                0            465.53      4.0            4.0              -1
3                0            417.55      1.0            2.0              -1
4                0            328.31      5.0           10.0              -1
...            ...               ...      ...            ...             ...
1920333          0           1815.46      2.0            8.0              -1
1920334          0            450.53      4.0           11.0               0
1920335          0            368.51      NaN            NaN               0
1920336          0            375.76      1.0            4.0              -1
1920337          0            289.32      3.0            4.0               0

[1920338 rows x 5 columns]

In [ ]:
df.select_dtypes(include='object')

,ChEMBL ID,Name,Synonyms,Type,AlogP,Polar Surface Area,HBA,HBD,#RO5 Violations,#Rotatable Bonds,...,Structure Type,Heavy Atoms,HBA (Lipinski),HBD (Lipinski),#RO5 Violations (Lipinski),Molecular Weight (Monoisotopic),Molecular Species,Molecular Formula,Smiles,Inchi Key
0,CHEMBL3425773,NaN,NaN,Small molecule,3.04,74.23,4,1,0,1,...,MOL,20,4,1,0,263.0582,ACID,C16H9NO3,N#Cc1ccc(-c2coc3cc(O)ccc3c2=O)cc1,VFISVTBQGUQPIQ-UHFFFAOYSA-N
1,CHEMBL1998753,NaN,NaN,Small molecule,2.28,100.60,9,0,0,7,...,MOL,33,9,0,0,455.158,NEUTRAL,C24H25NO8,COC(=O)[C@@H]1[C@H]2[C@H](OC(=O)c3ccccc3)CCN2O...,OQFYYDNHLYZLOL-BORCDFBASA-N
2,CHEMBL1867860,NaN,NaN,Small molecule,3.49,91.56,8,1,0,6,...,MOL,33,8,1,0,465.1358,NEUTRAL,C24H23N3O5S,COc1cccc(-n2c(=O)c3c(C)c(C)sc3n(CC(=O)Nc3ccccc...,CHCLAAKAFOYXSQ-UHFFFAOYSA-N
3,CHEMBL481686,NaN,NaN,Small molecule,4.71,48.71,4,1,0,6,...,MOL,31,5,1,0,417.2416,NEUTRAL,C26H31N3O2,Cc1cc(C)cc(N(Cc2ccc(CO)cc2)c2cc(C(=O)N3CCCC3)n...,UFQDWXYZGWHYFO-UHFFFAOYSA-N
4,CHEMBL1939547,NaN,NaN,Small molecule,3.69,112.06,7,0,0,4,...,MOL,23,8,0,0,328.0266,NEUTRAL,C14H8N4O4S,O=[N+]([O-])c1ccc(-c2nsc(-c3ccc([N+](=O)[O-])c...,VCXUCYVZJDYDCE-UHFFFAOYSA-N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1920333,CHEMBL1627004,NaN,NaN,Small molecule,None,None,None,None,None,None,...,MOL,None,None,None,None,1660.1316,None,C53H57N8Na7O39S7,CC(C)C[C@H](NC(=O)[C@H](CC(=O)OS(=O)(=O)[O-])N...,JSOUBHHWPCKVIR-CXTRJPRKSA-G
1920334,CHEMBL3958686,REMOGLIFLOZIN,REMOGLIFLOZIN|REMOGLIFLOZIN A,Small molecule,1.33,126.43,9,4,0,8,...,MOL,32,9,4,0,450.2366,NEUTRAL,C23H34N2O7,Cc1c(Cc2ccc(OC(C)C)cc2)c(O[C@@H]2O[C@H](CO)[C@...,GSINGUMRKGRYJP-VZWAGXQNSA-N
1920335,CHEMBL1201377,MISOPROSTOL ACID,Misoprostol acid|Misoprostolic acid|SC-30695,Small molecule,3.87,94.83,4,3,0,13,...,MOL,26,5,3,0,368.2563,ACID,C21H36O5,CCCCC(C)(O)C/C=C/[C@H]1[C@H](O)CC(=O)[C@@H]1CC...,CNWGPXZGIIOYDL-MKYGPDKMSA-N
1920336,CHEMBL537710,NaN,NaN,Small molecule,0.82,139.45,5,3,0,4,...,MOL,23,8,4,0,339.0325,ACID,C13H11ClFN3O5S,Cl.NS(=O)(=O)c1ccc(NC(=O)c2cccc(C(=O)O)n2)c(F)c1,QIHTWYBWQCJOMA-UHFFFAOYSA-N
1920337,CHEMBL906,MINOXIDIL SULFATE,MINOXIDIL SULFATE (SALT) 1:1|MINOXIDIL SULFATE...,Small molecule,-1.59,138.48,8,2,0,3,...,MOL,19,9,4,0,289.0845,ACID,C9H15N5O4S,Nc1cc(N2CCCCC2)nc(N)[n+]1OS(=O)(=O)[O-],OEOLOEUAGSPDLT-UHFFFAOYSA-N

In [ ]:
df.select_dtypes(exclude='number')

,ChEMBL ID,Name,Synonyms,Type,AlogP,Polar Surface Area,HBA,HBD,#RO5 Violations,#Rotatable Bonds,...,Structure Type,Heavy Atoms,HBA (Lipinski),HBD (Lipinski),#RO5 Violations (Lipinski),Molecular Weight (Monoisotopic),Molecular Species,Molecular Formula,Smiles,Inchi Key
0,CHEMBL3425773,NaN,NaN,Small molecule,3.04,74.23,4,1,0,1,...,MOL,20,4,1,0,263.0582,ACID,C16H9NO3,N#Cc1ccc(-c2coc3cc(O)ccc3c2=O)cc1,VFISVTBQGUQPIQ-UHFFFAOYSA-N
1,CHEMBL1998753,NaN,NaN,Small molecule,2.28,100.60,9,0,0,7,...,MOL,33,9,0,0,455.158,NEUTRAL,C24H25NO8,COC(=O)[C@@H]1[C@H]2[C@H](OC(=O)c3ccccc3)CCN2O...,OQFYYDNHLYZLOL-BORCDFBASA-N
2,CHEMBL1867860,NaN,NaN,Small molecule,3.49,91.56,8,1,0,6,...,MOL,33,8,1,0,465.1358,NEUTRAL,C24H23N3O5S,COc1cccc(-n2c(=O)c3c(C)c(C)sc3n(CC(=O)Nc3ccccc...,CHCLAAKAFOYXSQ-UHFFFAOYSA-N
3,CHEMBL481686,NaN,NaN,Small molecule,4.71,48.71,4,1,0,6,...,MOL,31,5,1,0,417.2416,NEUTRAL,C26H31N3O2,Cc1cc(C)cc(N(Cc2ccc(CO)cc2)c2cc(C(=O)N3CCCC3)n...,UFQDWXYZGWHYFO-UHFFFAOYSA-N
4,CHEMBL1939547,NaN,NaN,Small molecule,3.69,112.06,7,0,0,4,...,MOL,23,8,0,0,328.0266,NEUTRAL,C14H8N4O4S,O=[N+]([O-])c1ccc(-c2nsc(-c3ccc([N+](=O)[O-])c...,VCXUCYVZJDYDCE-UHFFFAOYSA-N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1920333,CHEMBL1627004,NaN,NaN,Small molecule,None,None,None,None,None,None,...,MOL,None,None,None,None,1660.1316,None,C53H57N8Na7O39S7,CC(C)C[C@H](NC(=O)[C@H](CC(=O)OS(=O)(=O)[O-])N...,JSOUBHHWPCKVIR-CXTRJPRKSA-G
1920334,CHEMBL3958686,REMOGLIFLOZIN,REMOGLIFLOZIN|REMOGLIFLOZIN A,Small molecule,1.33,126.43,9,4,0,8,...,MOL,32,9,4,0,450.2366,NEUTRAL,C23H34N2O7,Cc1c(Cc2ccc(OC(C)C)cc2)c(O[C@@H]2O[C@H](CO)[C@...,GSINGUMRKGRYJP-VZWAGXQNSA-N
1920335,CHEMBL1201377,MISOPROSTOL ACID,Misoprostol acid|Misoprostolic acid|SC-30695,Small molecule,3.87,94.83,4,3,0,13,...,MOL,26,5,3,0,368.2563,ACID,C21H36O5,CCCCC(C)(O)C/C=C/[C@H]1[C@H](O)CC(=O)[C@@H]1CC...,CNWGPXZGIIOYDL-MKYGPDKMSA-N
1920336,CHEMBL537710,NaN,NaN,Small molecule,0.82,139.45,5,3,0,4,...,MOL,23,8,4,0,339.0325,ACID,C13H11ClFN3O5S,Cl.NS(=O)(=O)c1ccc(NC(=O)c2cccc(C(=O)O)n2)c(F)c1,QIHTWYBWQCJOMA-UHFFFAOYSA-N
1920337,CHEMBL906,MINOXIDIL SULFATE,MINOXIDIL SULFATE (SALT) 1:1|MINOXIDIL SULFATE...,Small molecule,-1.59,138.48,8,2,0,3,...,MOL,19,9,4,0,289.0845,ACID,C9H15N5O4S,Nc1cc(N2CCCCC2)nc(N)[n+]1OS(=O)(=O)[O-],OEOLOEUAGSPDLT-UHFFFAOYSA-N

In [ ]:
df.describe()

,Max Phase,Molecular Weight,Targets,Bioactivities,Inorganic Flag
count,1.920338e+06,1.918253e+06,1.835637e+06,1.835637e+06,1.920338e+06
mean,1.114543e-02,4.184655e+02,6.528624e+00,9.748372e+00,-9.926633e-01
std,1.952130e-01,1.872083e+02,1.432113e+01,4.957730e+01,8.653368e-02
min,0.000000e+00,4.000000e+00,1.000000e+00,1.000000e+00,-1.000000e+00
25%,0.000000e+00,3.254500e+02,1.000000e+00,2.000000e+00,-1.000000e+00
50%,0.000000e+00,3.934100e+02,3.000000e+00,4.000000e+00,-1.000000e+00
75%,0.000000e+00,4.722000e+02,6.000000e+00,9.000000e+00,-1.000000e+00
max,4.000000e+00,1.254632e+04,1.332000e+03,1.778000e+04,1.000000e+00

In [ ]:
df.AlogP.value_counts()

None     31819
3.40      4851
3.30      4836
3.34      4766
3.47      4752
         ...
-7.03        1
-9.17        1
-7.21        1
14.71        1
-8.95        1
Name: AlogP, Length: 2476, dtype: int64

In [ ]:
df.AlogP.replace('None', np.nan, inplace=True)

In [ ]:
df.AlogP.astype(float)

0          3.04
1          2.28
2          3.49
3          4.71
4          3.69
           ...
1920333     NaN
1920334    1.33
1920335    3.87
1920336    0.82
1920337   -1.59
Name: AlogP, Length: 1920338, dtype: float64

In [ ]:
df.dtypes            # The dtype of the 'AlogP' column has not yet changed.

ChEMBL ID                           object
Name                                object
Synonyms                            object
Type                                object
Max Phase                            int64
Molecular Weight                   float64
Targets                            float64
Bioactivities                      float64
AlogP                               object
Polar Surface Area                  object
HBA                                 object
HBD                                 object
#RO5 Violations                     object
#Rotatable Bonds                    object
Passes Ro3                          object
QED Weighted                        object
CX Acidic pKa                       object
CX Basic pKa                        object
CX LogP                             object
CX LogD                             object
Aromatic Rings                      object
Structure Type                      object
Inorganic Flag                       int64
Heavy Atoms                         object
HBA (Lipinski)                      object
HBD (Lipinski)                      object
#RO5 Violations (Lipinski)          object
Molecular Weight (Monoisotopic)     object
Molecular Species                   object
Molecular Formula                   object
Smiles                              object
Inchi Key                           object
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1920338 entries, 0 to 1920337
Data columns (total 32 columns):
 #   Column                           Dtype
---  ------                           -----
 0   ChEMBL ID                        object
 1   Name                             object
 2   Synonyms                         object
 3   Type                             object
 4   Max Phase                        int64
 5   Molecular Weight                 float64
 6   Targets                          float64
 7   Bioactivities                    float64
 8   AlogP                            object
 9   Polar Surface Area               object
 10  HBA                              object
 11  HBD                              object
 12  #RO5 Violations                  object
 13  #Rotatable Bonds                 object
 14  Passes Ro3                       object
 15  QED Weighted                     object
 16  CX Acidic pKa                    object
 17  CX Basic pKa                     object
 18  CX LogP                          object
 19  CX LogD                          object
 20  Aromatic Rings                   object
 21  Structure Type                   object
 22  Inorganic Flag                   int64
 23  Heavy Atoms                      object
 24  HBA (Lipinski)                   object
 25  HBD (Lipinski)                   object
 26  #RO5 Violations (Lipinski)       object
 27  Molecular Weight (Monoisotopic)  object
 28  Molecular Species                object
 29  Molecular Formula                object
 30  Smiles                           object
 31  Inchi Key                        object
dtypes: float64(3), int64(2), object(27)
memory usage: 468.8+ MB

In [ ]:
df.AlogP.dtype

dtype('O')

In [ ]:
df['AlogP'] = df['AlogP'].astype(float) # To save changes. # You can also use df['AlogP'] = pd.to_numeric(df['AlogP'])

In [ ]:
df.dtypes             # As you can see, the dtype of the 'AlogP' column has been changed.

ChEMBL ID                           object
Name                                object
Synonyms                            object
Type                                object
Max Phase                            int64
Molecular Weight                   float64
Targets                            float64
Bioactivities                      float64
AlogP                              float64
Polar Surface Area                  object
HBA                                 object
HBD                                 object
#RO5 Violations                     object
#Rotatable Bonds                    object
Passes Ro3                          object
QED Weighted                        object
CX Acidic pKa                       object
CX Basic pKa                        object
CX LogP                             object
CX LogD                             object
Aromatic Rings                      object
Structure Type                      object
Inorganic Flag                       int64
Heavy Atoms                         object
HBA (Lipinski)                      object
HBD (Lipinski)                      object
#RO5 Violations (Lipinski)          object
Molecular Weight (Monoisotopic)     object
Molecular Species                   object
Molecular Formula                   object
Smiles                              object
Inchi Key                           object
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1920338 entries, 0 to 1920337
Data columns (total 32 columns):
 #   Column                           Dtype
---  ------                           -----
 0   ChEMBL ID                        object
 1   Name                             object
 2   Synonyms                         object
 3   Type                             object
 4   Max Phase                        int64
 5   Molecular Weight                 float64
 6   Targets                          float64
 7   Bioactivities                    float64
 8   AlogP                            float64
 9   Polar Surface Area               object
 10  HBA                              object
 11  HBD                              object
 12  #RO5 Violations                  object
 13  #Rotatable Bonds                 object
 14  Passes Ro3                       object
 15  QED Weighted                     object
 16  CX Acidic pKa                    object
 17  CX Basic pKa                     object
 18  CX LogP                          object
 19  CX LogD                          object
 20  Aromatic Rings                   object
 21  Structure Type                   object
 22  Inorganic Flag                   int64
 23  Heavy Atoms                      object
 24  HBA (Lipinski)                   object
 25  HBD (Lipinski)                   object
 26  #RO5 Violations (Lipinski)       object
 27  Molecular Weight (Monoisotopic)  object
 28  Molecular Species                object
 29  Molecular Formula                object
 30  Smiles                           object
 31  Inchi Key                        object
dtypes: float64(4), int64(2), object(26)
memory usage: 468.8+ MB

In [ ]:
df.AlogP.dtype

dtype('float64')

In [ ]:
df.describe()

,Max Phase,Molecular Weight,Targets,Bioactivities,AlogP,Inorganic Flag
count,1.920338e+06,1.918253e+06,1.835637e+06,1.835637e+06,1.886434e+06,1.920338e+06
mean,1.114543e-02,4.184655e+02,6.528624e+00,9.748372e+00,3.505533e+00,-9.926633e-01
std,1.952130e-01,1.872083e+02,1.432113e+01,4.957730e+01,1.883058e+00,8.653368e-02
min,0.000000e+00,4.000000e+00,1.000000e+00,1.000000e+00,-1.426000e+01,-1.000000e+00
25%,0.000000e+00,3.254500e+02,1.000000e+00,2.000000e+00,2.380000e+00,-1.000000e+00
50%,0.000000e+00,3.934100e+02,3.000000e+00,4.000000e+00,3.480000e+00,-1.000000e+00
75%,0.000000e+00,4.722000e+02,6.000000e+00,9.000000e+00,4.620000e+00,-1.000000e+00
max,4.000000e+00,1.254632e+04,1.332000e+03,1.778000e+04,2.257000e+01,1.000000e+00

In [ ]:
df.select_dtypes(include='number')

,Max Phase,Molecular Weight,Targets,Bioactivities,AlogP,Inorganic Flag
0,0,263.25,1.0,1.0,3.04,-1
1,0,455.46,56.0,56.0,2.28,-1
2,0,465.53,4.0,4.0,3.49,-1
3,0,417.55,1.0,2.0,4.71,-1
4,0,328.31,5.0,10.0,3.69,-1
...,...,...,...,...,...,...
1920333,0,1815.46,2.0,8.0,NaN,-1
1920334,0,450.53,4.0,11.0,1.33,0
1920335,0,368.51,NaN,NaN,3.87,0
1920336,0,375.76,1.0,4.0,0.82,-1
1920337,0,289.32,3.0,4.0,-1.59,0