### Selecting rows and columns by labels and positions using loc[ ] and iloc[ ] functions(slicing)

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('/content/drive/MyDrive/Chembl_library_2M.csv', sep=';')
df.head()

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:3326: DtypeWarning: Columns (27) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,ChEMBL ID,Name,Synonyms,Type,Max Phase,Molecular Weight,Targets,Bioactivities,AlogP,Polar Surface Area,...,Inorganic Flag,Heavy Atoms,HBA (Lipinski),HBD (Lipinski),#RO5 Violations (Lipinski),Molecular Weight (Monoisotopic),Molecular Species,Molecular Formula,Smiles,Inchi Key
0,CHEMBL3425773,NaN,NaN,Small molecule,0,263.25,1.0,1.0,3.04,74.23,...,-1,20,4,1,0,263.0582,ACID,C16H9NO3,N#Cc1ccc(-c2coc3cc(O)ccc3c2=O)cc1,VFISVTBQGUQPIQ-UHFFFAOYSA-N
1,CHEMBL1998753,NaN,NaN,Small molecule,0,455.46,56.0,56.0,2.28,100.60,...,-1,33,9,0,0,455.158,NEUTRAL,C24H25NO8,COC(=O)[C@@H]1[C@H]2[C@H](OC(=O)c3ccccc3)CCN2O...,OQFYYDNHLYZLOL-BORCDFBASA-N
2,CHEMBL1867860,NaN,NaN,Small molecule,0,465.53,4.0,4.0,3.49,91.56,...,-1,33,8,1,0,465.1358,NEUTRAL,C24H23N3O5S,COc1cccc(-n2c(=O)c3c(C)c(C)sc3n(CC(=O)Nc3ccccc...,CHCLAAKAFOYXSQ-UHFFFAOYSA-N
3,CHEMBL481686,NaN,NaN,Small molecule,0,417.55,1.0,2.0,4.71,48.71,...,-1,31,5,1,0,417.2416,NEUTRAL,C26H31N3O2,Cc1cc(C)cc(N(Cc2ccc(CO)cc2)c2cc(C(=O)N3CCCC3)n...,UFQDWXYZGWHYFO-UHFFFAOYSA-N
4,CHEMBL1939547,NaN,NaN,Small molecule,0,328.31,5.0,10.0,3.69,112.06,...,-1,23,8,0,0,328.0266,NEUTRAL,C14H8N4O4S,O=[N+]([O-])c1ccc(-c2nsc(-c3ccc([N+](=O)[O-])c...,VCXUCYVZJDYDCE-UHFFFAOYSA-N

In [3]:
df.loc[:, ['Synonyms', 'Name']]

                                                  Synonyms               Name
0                                                      NaN                NaN
1                                                      NaN                NaN
2                                                      NaN                NaN
3                                                      NaN                NaN
4                                                      NaN                NaN
...                                                    ...                ...
1920333                                                NaN                NaN
1920334                      REMOGLIFLOZIN|REMOGLIFLOZIN A      REMOGLIFLOZIN
1920335       Misoprostol acid|Misoprostolic acid|SC-30695   MISOPROSTOL ACID
1920336                                                NaN                NaN
1920337  MINOXIDIL SULFATE (SALT) 1:1|MINOXIDIL SULFATE...  MINOXIDIL SULFATE

[1920338 rows x 2 columns]

In [4]:
df.iloc[:, [2, 1]]

                                                  Synonyms               Name
0                                                      NaN                NaN
1                                                      NaN                NaN
2                                                      NaN                NaN
3                                                      NaN                NaN
4                                                      NaN                NaN
...                                                    ...                ...
1920333                                                NaN                NaN
1920334                      REMOGLIFLOZIN|REMOGLIFLOZIN A      REMOGLIFLOZIN
1920335       Misoprostol acid|Misoprostolic acid|SC-30695   MISOPROSTOL ACID
1920336                                                NaN                NaN
1920337  MINOXIDIL SULFATE (SALT) 1:1|MINOXIDIL SULFATE...  MINOXIDIL SULFATE

[1920338 rows x 2 columns]

In [5]:
df.loc[:, 'Name':'HBA'] # Select columns between two columns

,Name,Synonyms,Type,Max Phase,Molecular Weight,Targets,Bioactivities,AlogP,Polar Surface Area,HBA
0,NaN,NaN,Small molecule,0,263.25,1.0,1.0,3.04,74.23,4
1,NaN,NaN,Small molecule,0,455.46,56.0,56.0,2.28,100.60,9
2,NaN,NaN,Small molecule,0,465.53,4.0,4.0,3.49,91.56,8
3,NaN,NaN,Small molecule,0,417.55,1.0,2.0,4.71,48.71,4
4,NaN,NaN,Small molecule,0,328.31,5.0,10.0,3.69,112.06,7
...,...,...,...,...,...,...,...,...,...,...
1920333,NaN,NaN,Small molecule,0,1815.46,2.0,8.0,None,None,None
1920334,REMOGLIFLOZIN,REMOGLIFLOZIN|REMOGLIFLOZIN A,Small molecule,0,450.53,4.0,11.0,1.33,126.43,9
1920335,MISOPROSTOL ACID,Misoprostol acid|Misoprostolic acid|SC-30695,Small molecule,0,368.51,NaN,NaN,3.87,94.83,4
1920336,NaN,NaN,Small molecule,0,375.76,1.0,4.0,0.82,139.45,5
1920337,MINOXIDIL SULFATE,MINOXIDIL SULFATE (SALT) 1:1|MINOXIDIL SULFATE...,Small molecule,0,289.32,3.0,4.0,-1.59,138.48,8

In [6]:
df.iloc[:, 1 : 11]

,Name,Synonyms,Type,Max Phase,Molecular Weight,Targets,Bioactivities,AlogP,Polar Surface Area,HBA
0,NaN,NaN,Small molecule,0,263.25,1.0,1.0,3.04,74.23,4
1,NaN,NaN,Small molecule,0,455.46,56.0,56.0,2.28,100.60,9
2,NaN,NaN,Small molecule,0,465.53,4.0,4.0,3.49,91.56,8
3,NaN,NaN,Small molecule,0,417.55,1.0,2.0,4.71,48.71,4
4,NaN,NaN,Small molecule,0,328.31,5.0,10.0,3.69,112.06,7
...,...,...,...,...,...,...,...,...,...,...
1920333,NaN,NaN,Small molecule,0,1815.46,2.0,8.0,None,None,None
1920334,REMOGLIFLOZIN,REMOGLIFLOZIN|REMOGLIFLOZIN A,Small molecule,0,450.53,4.0,11.0,1.33,126.43,9
1920335,MISOPROSTOL ACID,Misoprostol acid|Misoprostolic acid|SC-30695,Small molecule,0,368.51,NaN,NaN,3.87,94.83,4
1920336,NaN,NaN,Small molecule,0,375.76,1.0,4.0,0.82,139.45,5
1920337,MINOXIDIL SULFATE,MINOXIDIL SULFATE (SALT) 1:1|MINOXIDIL SULFATE...,Small molecule,0,289.32,3.0,4.0,-1.59,138.48,8

In [7]:
df.loc[:, 'HBA':]        # Select columns by range

,HBA,HBD,#RO5 Violations,#Rotatable Bonds,Passes Ro3,QED Weighted,CX Acidic pKa,CX Basic pKa,CX LogP,CX LogD,...,Inorganic Flag,Heavy Atoms,HBA (Lipinski),HBD (Lipinski),#RO5 Violations (Lipinski),Molecular Weight (Monoisotopic),Molecular Species,Molecular Formula,Smiles,Inchi Key
0,4,1,0,1,N,0.73,6.23,None,2.89,1.73,...,-1,20,4,1,0,263.0582,ACID,C16H9NO3,N#Cc1ccc(-c2coc3cc(O)ccc3c2=O)cc1,VFISVTBQGUQPIQ-UHFFFAOYSA-N
1,9,0,0,7,N,0.46,None,None,3.10,3.10,...,-1,33,9,0,0,455.158,NEUTRAL,C24H25NO8,COC(=O)[C@@H]1[C@H]2[C@H](OC(=O)c3ccccc3)CCN2O...,OQFYYDNHLYZLOL-BORCDFBASA-N
2,8,1,0,6,N,0.47,11.11,None,4.20,4.20,...,-1,33,8,1,0,465.1358,NEUTRAL,C24H23N3O5S,COc1cccc(-n2c(=O)c3c(C)c(C)sc3n(CC(=O)Nc3ccccc...,CHCLAAKAFOYXSQ-UHFFFAOYSA-N
3,4,1,0,6,N,0.63,None,None,4.55,4.55,...,-1,31,5,1,0,417.2416,NEUTRAL,C26H31N3O2,Cc1cc(C)cc(N(Cc2ccc(CO)cc2)c2cc(C(=O)N3CCCC3)n...,UFQDWXYZGWHYFO-UHFFFAOYSA-N
4,7,0,0,4,N,0.53,None,0.27,4.50,4.50,...,-1,23,8,0,0,328.0266,NEUTRAL,C14H8N4O4S,O=[N+]([O-])c1ccc(-c2nsc(-c3ccc([N+](=O)[O-])c...,VCXUCYVZJDYDCE-UHFFFAOYSA-N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1920333,None,None,None,None,None,None,None,None,None,None,...,-1,None,None,None,None,1660.1316,None,C53H57N8Na7O39S7,CC(C)C[C@H](NC(=O)[C@H](CC(=O)OS(=O)(=O)[O-])N...,JSOUBHHWPCKVIR-CXTRJPRKSA-G
1920334,9,4,0,8,N,0.47,12.20,1.13,2.10,2.10,...,0,32,9,4,0,450.2366,NEUTRAL,C23H34N2O7,Cc1c(Cc2ccc(OC(C)C)cc2)c(O[C@@H]2O[C@H](CO)[C@...,GSINGUMRKGRYJP-VZWAGXQNSA-N
1920335,4,3,0,13,N,0.34,4.35,None,3.71,0.79,...,0,26,5,3,0,368.2563,ACID,C21H36O5,CCCCC(C)(O)C/C=C/[C@H]1[C@H](O)CC(=O)[C@@H]1CC...,CNWGPXZGIIOYDL-MKYGPDKMSA-N
1920336,5,3,0,4,N,0.75,0.86,4.65,0.00,-2.31,...,-1,23,8,4,0,339.0325,ACID,C13H11ClFN3O5S,Cl.NS(=O)(=O)c1ccc(NC(=O)c2cccc(C(=O)O)n2)c(F)c1,QIHTWYBWQCJOMA-UHFFFAOYSA-N
1920337,8,2,0,3,N,0.39,-3.04,None,-0.87,-0.78,...,0,19,9,4,0,289.0845,ACID,C9H15N5O4S,Nc1cc(N2CCCCC2)nc(N)[n+]1OS(=O)(=O)[O-],OEOLOEUAGSPDLT-UHFFFAOYSA-N

In [8]:
df.iloc[:, 10:]

,HBA,HBD,#RO5 Violations,#Rotatable Bonds,Passes Ro3,QED Weighted,CX Acidic pKa,CX Basic pKa,CX LogP,CX LogD,...,Inorganic Flag,Heavy Atoms,HBA (Lipinski),HBD (Lipinski),#RO5 Violations (Lipinski),Molecular Weight (Monoisotopic),Molecular Species,Molecular Formula,Smiles,Inchi Key
0,4,1,0,1,N,0.73,6.23,None,2.89,1.73,...,-1,20,4,1,0,263.0582,ACID,C16H9NO3,N#Cc1ccc(-c2coc3cc(O)ccc3c2=O)cc1,VFISVTBQGUQPIQ-UHFFFAOYSA-N
1,9,0,0,7,N,0.46,None,None,3.10,3.10,...,-1,33,9,0,0,455.158,NEUTRAL,C24H25NO8,COC(=O)[C@@H]1[C@H]2[C@H](OC(=O)c3ccccc3)CCN2O...,OQFYYDNHLYZLOL-BORCDFBASA-N
2,8,1,0,6,N,0.47,11.11,None,4.20,4.20,...,-1,33,8,1,0,465.1358,NEUTRAL,C24H23N3O5S,COc1cccc(-n2c(=O)c3c(C)c(C)sc3n(CC(=O)Nc3ccccc...,CHCLAAKAFOYXSQ-UHFFFAOYSA-N
3,4,1,0,6,N,0.63,None,None,4.55,4.55,...,-1,31,5,1,0,417.2416,NEUTRAL,C26H31N3O2,Cc1cc(C)cc(N(Cc2ccc(CO)cc2)c2cc(C(=O)N3CCCC3)n...,UFQDWXYZGWHYFO-UHFFFAOYSA-N
4,7,0,0,4,N,0.53,None,0.27,4.50,4.50,...,-1,23,8,0,0,328.0266,NEUTRAL,C14H8N4O4S,O=[N+]([O-])c1ccc(-c2nsc(-c3ccc([N+](=O)[O-])c...,VCXUCYVZJDYDCE-UHFFFAOYSA-N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1920333,None,None,None,None,None,None,None,None,None,None,...,-1,None,None,None,None,1660.1316,None,C53H57N8Na7O39S7,CC(C)C[C@H](NC(=O)[C@H](CC(=O)OS(=O)(=O)[O-])N...,JSOUBHHWPCKVIR-CXTRJPRKSA-G
1920334,9,4,0,8,N,0.47,12.20,1.13,2.10,2.10,...,0,32,9,4,0,450.2366,NEUTRAL,C23H34N2O7,Cc1c(Cc2ccc(OC(C)C)cc2)c(O[C@@H]2O[C@H](CO)[C@...,GSINGUMRKGRYJP-VZWAGXQNSA-N
1920335,4,3,0,13,N,0.34,4.35,None,3.71,0.79,...,0,26,5,3,0,368.2563,ACID,C21H36O5,CCCCC(C)(O)C/C=C/[C@H]1[C@H](O)CC(=O)[C@@H]1CC...,CNWGPXZGIIOYDL-MKYGPDKMSA-N
1920336,5,3,0,4,N,0.75,0.86,4.65,0.00,-2.31,...,-1,23,8,4,0,339.0325,ACID,C13H11ClFN3O5S,Cl.NS(=O)(=O)c1ccc(NC(=O)c2cccc(C(=O)O)n2)c(F)c1,QIHTWYBWQCJOMA-UHFFFAOYSA-N
1920337,8,2,0,3,N,0.39,-3.04,None,-0.87,-0.78,...,0,19,9,4,0,289.0845,ACID,C9H15N5O4S,Nc1cc(N2CCCCC2)nc(N)[n+]1OS(=O)(=O)[O-],OEOLOEUAGSPDLT-UHFFFAOYSA-N

In [9]:
df.loc[:, :'HBA']       # Select columns by range

,ChEMBL ID,Name,Synonyms,Type,Max Phase,Molecular Weight,Targets,Bioactivities,AlogP,Polar Surface Area,HBA
0,CHEMBL3425773,NaN,NaN,Small molecule,0,263.25,1.0,1.0,3.04,74.23,4
1,CHEMBL1998753,NaN,NaN,Small molecule,0,455.46,56.0,56.0,2.28,100.60,9
2,CHEMBL1867860,NaN,NaN,Small molecule,0,465.53,4.0,4.0,3.49,91.56,8
3,CHEMBL481686,NaN,NaN,Small molecule,0,417.55,1.0,2.0,4.71,48.71,4
4,CHEMBL1939547,NaN,NaN,Small molecule,0,328.31,5.0,10.0,3.69,112.06,7
...,...,...,...,...,...,...,...,...,...,...,...
1920333,CHEMBL1627004,NaN,NaN,Small molecule,0,1815.46,2.0,8.0,None,None,None
1920334,CHEMBL3958686,REMOGLIFLOZIN,REMOGLIFLOZIN|REMOGLIFLOZIN A,Small molecule,0,450.53,4.0,11.0,1.33,126.43,9
1920335,CHEMBL1201377,MISOPROSTOL ACID,Misoprostol acid|Misoprostolic acid|SC-30695,Small molecule,0,368.51,NaN,NaN,3.87,94.83,4
1920336,CHEMBL537710,NaN,NaN,Small molecule,0,375.76,1.0,4.0,0.82,139.45,5
1920337,CHEMBL906,MINOXIDIL SULFATE,MINOXIDIL SULFATE (SALT) 1:1|MINOXIDIL SULFATE...,Small molecule,0,289.32,3.0,4.0,-1.59,138.48,8

In [10]:
df.iloc[:, :11]

,ChEMBL ID,Name,Synonyms,Type,Max Phase,Molecular Weight,Targets,Bioactivities,AlogP,Polar Surface Area,HBA
0,CHEMBL3425773,NaN,NaN,Small molecule,0,263.25,1.0,1.0,3.04,74.23,4
1,CHEMBL1998753,NaN,NaN,Small molecule,0,455.46,56.0,56.0,2.28,100.60,9
2,CHEMBL1867860,NaN,NaN,Small molecule,0,465.53,4.0,4.0,3.49,91.56,8
3,CHEMBL481686,NaN,NaN,Small molecule,0,417.55,1.0,2.0,4.71,48.71,4
4,CHEMBL1939547,NaN,NaN,Small molecule,0,328.31,5.0,10.0,3.69,112.06,7
...,...,...,...,...,...,...,...,...,...,...,...
1920333,CHEMBL1627004,NaN,NaN,Small molecule,0,1815.46,2.0,8.0,None,None,None
1920334,CHEMBL3958686,REMOGLIFLOZIN,REMOGLIFLOZIN|REMOGLIFLOZIN A,Small molecule,0,450.53,4.0,11.0,1.33,126.43,9
1920335,CHEMBL1201377,MISOPROSTOL ACID,Misoprostol acid|Misoprostolic acid|SC-30695,Small molecule,0,368.51,NaN,NaN,3.87,94.83,4
1920336,CHEMBL537710,NaN,NaN,Small molecule,0,375.76,1.0,4.0,0.82,139.45,5
1920337,CHEMBL906,MINOXIDIL SULFATE,MINOXIDIL SULFATE (SALT) 1:1|MINOXIDIL SULFATE...,Small molecule,0,289.32,3.0,4.0,-1.59,138.48,8

In [11]:
df.iloc[:, -1]

0          VFISVTBQGUQPIQ-UHFFFAOYSA-N
1          OQFYYDNHLYZLOL-BORCDFBASA-N
2          CHCLAAKAFOYXSQ-UHFFFAOYSA-N
3          UFQDWXYZGWHYFO-UHFFFAOYSA-N
4          VCXUCYVZJDYDCE-UHFFFAOYSA-N
                      ...
1920333    JSOUBHHWPCKVIR-CXTRJPRKSA-G
1920334    GSINGUMRKGRYJP-VZWAGXQNSA-N
1920335    CNWGPXZGIIOYDL-MKYGPDKMSA-N
1920336    QIHTWYBWQCJOMA-UHFFFAOYSA-N
1920337    OEOLOEUAGSPDLT-UHFFFAOYSA-N
Name: Inchi Key, Length: 1920338, dtype: object

In [12]:
df.iloc[:, -1:]

                           Inchi Key
0        VFISVTBQGUQPIQ-UHFFFAOYSA-N
1        OQFYYDNHLYZLOL-BORCDFBASA-N
2        CHCLAAKAFOYXSQ-UHFFFAOYSA-N
3        UFQDWXYZGWHYFO-UHFFFAOYSA-N
4        VCXUCYVZJDYDCE-UHFFFAOYSA-N
...                              ...
1920333  JSOUBHHWPCKVIR-CXTRJPRKSA-G
1920334  GSINGUMRKGRYJP-VZWAGXQNSA-N
1920335  CNWGPXZGIIOYDL-MKYGPDKMSA-N
1920336  QIHTWYBWQCJOMA-UHFFFAOYSA-N
1920337  OEOLOEUAGSPDLT-UHFFFAOYSA-N

[1920338 rows x 1 columns]

In [13]:
df.iloc[:, -3:]

,Molecular Formula,Smiles,Inchi Key
0,C16H9NO3,N#Cc1ccc(-c2coc3cc(O)ccc3c2=O)cc1,VFISVTBQGUQPIQ-UHFFFAOYSA-N
1,C24H25NO8,COC(=O)[C@@H]1[C@H]2[C@H](OC(=O)c3ccccc3)CCN2O...,OQFYYDNHLYZLOL-BORCDFBASA-N
2,C24H23N3O5S,COc1cccc(-n2c(=O)c3c(C)c(C)sc3n(CC(=O)Nc3ccccc...,CHCLAAKAFOYXSQ-UHFFFAOYSA-N
3,C26H31N3O2,Cc1cc(C)cc(N(Cc2ccc(CO)cc2)c2cc(C(=O)N3CCCC3)n...,UFQDWXYZGWHYFO-UHFFFAOYSA-N
4,C14H8N4O4S,O=[N+]([O-])c1ccc(-c2nsc(-c3ccc([N+](=O)[O-])c...,VCXUCYVZJDYDCE-UHFFFAOYSA-N
...,...,...,...
1920333,C53H57N8Na7O39S7,CC(C)C[C@H](NC(=O)[C@H](CC(=O)OS(=O)(=O)[O-])N...,JSOUBHHWPCKVIR-CXTRJPRKSA-G
1920334,C23H34N2O7,Cc1c(Cc2ccc(OC(C)C)cc2)c(O[C@@H]2O[C@H](CO)[C@...,GSINGUMRKGRYJP-VZWAGXQNSA-N
1920335,C21H36O5,CCCCC(C)(O)C/C=C/[C@H]1[C@H](O)CC(=O)[C@@H]1CC...,CNWGPXZGIIOYDL-MKYGPDKMSA-N
1920336,C13H11ClFN3O5S,Cl.NS(=O)(=O)c1ccc(NC(=O)c2cccc(C(=O)O)n2)c(F)c1,QIHTWYBWQCJOMA-UHFFFAOYSA-N
1920337,C9H15N5O4S,Nc1cc(N2CCCCC2)nc(N)[n+]1OS(=O)(=O)[O-],OEOLOEUAGSPDLT-UHFFFAOYSA-N

In [14]:
df.iloc[-1,]

ChEMBL ID                                                                  CHEMBL906
Name                                                               MINOXIDIL SULFATE
Synonyms                           MINOXIDIL SULFATE (SALT) 1:1|MINOXIDIL SULFATE...
Type                                                                  Small molecule
Max Phase                                                                          0
Molecular Weight                                                              289.32
Targets                                                                          3.0
Bioactivities                                                                    4.0
AlogP                                                                          -1.59
Polar Surface Area                                                            138.48
HBA                                                                                8
HBD                                                                                2
#RO5 Violations                                                                    0
#Rotatable Bonds                                                                   3
Passes Ro3                                                                         N
QED Weighted                                                                    0.39
CX Acidic pKa                                                                  -3.04
CX Basic pKa                                                                    None
CX LogP                                                                        -0.87
CX LogD                                                                        -0.78
Aromatic Rings                                                                     1
Structure Type                                                                   MOL
Inorganic Flag                                                                     0
Heavy Atoms                                                                       19
HBA (Lipinski)                                                                     9
HBD (Lipinski)                                                                     4
#RO5 Violations (Lipinski)                                                         0
Molecular Weight (Monoisotopic)                                             289.0845
Molecular Species                                                               ACID
Molecular Formula                                                         C9H15N5O4S
Smiles                                       Nc1cc(N2CCCCC2)nc(N)[n+]1OS(=O)(=O)[O-]
Inchi Key                                                OEOLOEUAGSPDLT-UHFFFAOYSA-N
Name: 1920337, dtype: object

In [15]:
df.iloc[-1:]

,ChEMBL ID,Name,Synonyms,Type,Max Phase,Molecular Weight,Targets,Bioactivities,AlogP,Polar Surface Area,...,Inorganic Flag,Heavy Atoms,HBA (Lipinski),HBD (Lipinski),#RO5 Violations (Lipinski),Molecular Weight (Monoisotopic),Molecular Species,Molecular Formula,Smiles,Inchi Key
1920337,CHEMBL906,MINOXIDIL SULFATE,MINOXIDIL SULFATE (SALT) 1:1|MINOXIDIL SULFATE...,Small molecule,0,289.32,3.0,4.0,-1.59,138.48,...,0,19,9,4,0,289.0845,ACID,C9H15N5O4S,Nc1cc(N2CCCCC2)nc(N)[n+]1OS(=O)(=O)[O-],OEOLOEUAGSPDLT-UHFFFAOYSA-N

In [16]:
df.iloc[-3:]

,ChEMBL ID,Name,Synonyms,Type,Max Phase,Molecular Weight,Targets,Bioactivities,AlogP,Polar Surface Area,...,Inorganic Flag,Heavy Atoms,HBA (Lipinski),HBD (Lipinski),#RO5 Violations (Lipinski),Molecular Weight (Monoisotopic),Molecular Species,Molecular Formula,Smiles,Inchi Key
1920335,CHEMBL1201377,MISOPROSTOL ACID,Misoprostol acid|Misoprostolic acid|SC-30695,Small molecule,0,368.51,NaN,NaN,3.87,94.83,...,0,26,5,3,0,368.2563,ACID,C21H36O5,CCCCC(C)(O)C/C=C/[C@H]1[C@H](O)CC(=O)[C@@H]1CC...,CNWGPXZGIIOYDL-MKYGPDKMSA-N
1920336,CHEMBL537710,NaN,NaN,Small molecule,0,375.76,1.0,4.0,0.82,139.45,...,-1,23,8,4,0,339.0325,ACID,C13H11ClFN3O5S,Cl.NS(=O)(=O)c1ccc(NC(=O)c2cccc(C(=O)O)n2)c(F)c1,QIHTWYBWQCJOMA-UHFFFAOYSA-N
1920337,CHEMBL906,MINOXIDIL SULFATE,MINOXIDIL SULFATE (SALT) 1:1|MINOXIDIL SULFATE...,Small molecule,0,289.32,3.0,4.0,-1.59,138.48,...,0,19,9,4,0,289.0845,ACID,C9H15N5O4S,Nc1cc(N2CCCCC2)nc(N)[n+]1OS(=O)(=O)[O-],OEOLOEUAGSPDLT-UHFFFAOYSA-N

In [17]:
df.iloc[::4]

,ChEMBL ID,Name,Synonyms,Type,Max Phase,Molecular Weight,Targets,Bioactivities,AlogP,Polar Surface Area,...,Inorganic Flag,Heavy Atoms,HBA (Lipinski),HBD (Lipinski),#RO5 Violations (Lipinski),Molecular Weight (Monoisotopic),Molecular Species,Molecular Formula,Smiles,Inchi Key
0,CHEMBL3425773,NaN,NaN,Small molecule,0,263.25,1.0,1.0,3.04,74.23,...,-1,20,4,1,0,263.0582,ACID,C16H9NO3,N#Cc1ccc(-c2coc3cc(O)ccc3c2=O)cc1,VFISVTBQGUQPIQ-UHFFFAOYSA-N
4,CHEMBL1939547,NaN,NaN,Small molecule,0,328.31,5.0,10.0,3.69,112.06,...,-1,23,8,0,0,328.0266,NEUTRAL,C14H8N4O4S,O=[N+]([O-])c1ccc(-c2nsc(-c3ccc([N+](=O)[O-])c...,VCXUCYVZJDYDCE-UHFFFAOYSA-N
8,CHEMBL1705516,NaN,NaN,Small molecule,0,263.35,5.0,5.0,1.11,61.36,...,-1,19,6,1,0,263.1746,NEUTRAL,C13H21N5O,CCCCNC(=O)N1CCN(c2ncccn2)CC1,XCJGSTNQIYNLRB-UHFFFAOYSA-N
12,CHEMBL49416,NaN,NaN,Small molecule,0,279.30,1.0,2.0,0.98,79.90,...,-1,20,7,2,0,279.1219,NEUTRAL,C13H17N3O4,CC(=O)Nc1ccc(OC(=O)NN2CCOCC2)cc1,MFJWHBDRNLMBHO-UHFFFAOYSA-N
16,CHEMBL1488309,NaN,NaN,Small molecule,0,379.37,7.0,7.0,0.45,111.45,...,-1,27,10,0,0,379.138,NEUTRAL,C17H21N3O7,O=C(OCC(=O)N1CCOCC1)c1ccc(N2CCOCC2)c([N+](=O)[...,UNEHDXLCONOHFK-UHFFFAOYSA-N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1920320,CHEMBL2093873,NaN,NaN,Small molecule,0,335.87,1.0,4.0,3.81,46.25,...,-1,21,2,3,0,281.178,BASE,C19H26ClNO2,Cc1cc(C)c2c(c1O)C(N)C(C)(Cc1ccccc1)C2.Cl.O,VKGKZTVMVWMPPO-UHFFFAOYSA-N
1920324,CHEMBL3794004,NaN,NaN,Small molecule,0,634.26,3.0,4.0,4.54,87.23,...,-1,41,8,0,1,597.2331,NEUTRAL,C31H40ClN3O5S2,C=C1CN(S(=O)(=O)c2ccc(C)cc2)CCCN(Cc2ccccc2)CCC...,MVQDIABQVAUPIX-UHFFFAOYSA-N
1920328,CHEMBL538473,NaN,NaN,Small molecule,0,583.51,1.0,2.0,3.19,98.72,...,-1,37,9,2,1,510.2366,NEUTRAL,C28H36Cl2N2O7,COc1cc([C@@H]2c3cc4c(cc3[C@@H](NCCN3CCCCC3)[C@...,QLSVHEVTXRGFGO-PJFAXEIZSA-N
1920332,CHEMBL3318948,NaN,NaN,Small molecule,0,638.76,1.0,6.0,3.50,92.79,...,-1,35,8,2,0,488.3363,BASE,C31H50N4O10,CCOC[C@@H](CC(C)C)NC(=O)[C@@H]1CNC[C@H](C(=O)N...,PCQFCXPXHUDXCJ-HWAJWLCKSA-N
1920336,CHEMBL537710,NaN,NaN,Small molecule,0,375.76,1.0,4.0,0.82,139.45,...,-1,23,8,4,0,339.0325,ACID,C13H11ClFN3O5S,Cl.NS(=O)(=O)c1ccc(NC(=O)c2cccc(C(=O)O)n2)c(F)c1,QIHTWYBWQCJOMA-UHFFFAOYSA-N

In [18]:
df.describe()

,Max Phase,Molecular Weight,Targets,Bioactivities,Inorganic Flag
count,1.920338e+06,1.918253e+06,1.835637e+06,1.835637e+06,1.920338e+06
mean,1.114543e-02,4.184655e+02,6.528624e+00,9.748372e+00,-9.926633e-01
std,1.952130e-01,1.872083e+02,1.432113e+01,4.957730e+01,8.653368e-02
min,0.000000e+00,4.000000e+00,1.000000e+00,1.000000e+00,-1.000000e+00
25%,0.000000e+00,3.254500e+02,1.000000e+00,2.000000e+00,-1.000000e+00
50%,0.000000e+00,3.934100e+02,3.000000e+00,4.000000e+00,-1.000000e+00
75%,0.000000e+00,4.722000e+02,6.000000e+00,9.000000e+00,-1.000000e+00
max,4.000000e+00,1.254632e+04,1.332000e+03,1.778000e+04,1.000000e+00

In [19]:
df.describe().loc['min':'max']

     Max Phase  Molecular Weight  Targets  Bioactivities  Inorganic Flag
min        0.0              4.00      1.0            1.0            -1.0
25%        0.0            325.45      1.0            2.0            -1.0
50%        0.0            393.41      3.0            4.0            -1.0
75%        0.0            472.20      6.0            9.0            -1.0
max        4.0          12546.32   1332.0        17780.0             1.0

In [20]:
df.describe().loc['min':'max', 'Molecular Weight':'Bioactivities']

     Molecular Weight  Targets  Bioactivities
min              4.00      1.0            1.0
25%            325.45      1.0            2.0
50%            393.41      3.0            4.0
75%            472.20      6.0            9.0
max          12546.32   1332.0        17780.0